### ISSUE TITLE
Rows cannot be editted while search is active

### ISSUE THREAD

**Issue by pan-alex** [NadavShaar/react-grid-table#103] opened 2022-10-26 22:02 UTC
While search filters are active, rows cannot be edited. I am not sure if this behaviour is intentional.

This can be reproduced in the [demo](https://nadavshaar.github.io/react-grid-table/):
1. Type at least 2 characters into the search bar so that search filtering is active
2. Click edit button on a row
3. Attempt to change the value of one of the input fields -> value of the field does not change. E.g., text fields do not update on keystroke; select fields cannot be changed.

**Comment by NadavShaar** [comment] 2022-10-26 22:26
This is a bug (duplicate of #93), a fix is coming soon.

**Closed** 2022-10-26 22:27 UTC
